"""WAP/1.0 specification layer: wire models, signatures and proof-of-work."""

from .conversation import ConversationGuard, ConversationLimitError, ConversationPolicy
from .crypto import (
    KeyFormatError,
    KeyPair,
    Signer,
    canonical_json,
    fingerprint,
    generate_keypair,
    sign_model,
    signing_payload,
    verify_bytes,
    verify_model,
)
from .models import (
    CHALLENGE_PATH,
    HEADER_AGENT_KEY,
    HEADER_SIGNATURE,
    HEADER_VERSION,
    INTERACT_PATH,
    WAP_VERSION,
    WELL_KNOWN_PATH,
    AgentManifest,
    AgentMessage,
    Capability,
    Challenge,
    ErrorCode,
    ErrorDetail,
    ErrorResponse,
    RateLimitPolicy,
    Role,
    StreamEventType,
    normalize_authority,
)
from .pow import PowEngine, PowError, check_solution, solve, solve_async

__all__ = [
    "CHALLENGE_PATH",
    "HEADER_AGENT_KEY",
    "HEADER_SIGNATURE",
    "HEADER_VERSION",
    "INTERACT_PATH",
    "WAP_VERSION",
    "WELL_KNOWN_PATH",
    "AgentManifest",
    "AgentMessage",
    "Capability",
    "Challenge",
    "ConversationGuard",
    "ConversationLimitError",
    "ConversationPolicy",
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "KeyFormatError",
    "KeyPair",
    "PowEngine",
    "PowError",
    "RateLimitPolicy",
    "Role",
    "Signer",
    "StreamEventType",
    "canonical_json",
    "check_solution",
    "fingerprint",
    "generate_keypair",
    "normalize_authority",
    "sign_model",
    "signing_payload",
    "solve",
    "solve_async",
    "verify_bytes",
    "verify_model",
]
